declare namespace Cloudflare {
  interface Env {
    DB: D1Database;
    ARTIFACTS: R2Bucket;
    MARKETPLACE_ARTIFACT_KEY?: string;
    MARKETPLACE_CREDENTIAL_KEY?: string;
    MARKETPLACE_CREDENTIAL_KEYRING?: string;
    MARKETPLACE_CREDENTIAL_KEYRING_MANIFEST?: string;
    MARKETPLACE_CREDENTIAL_KEY_SLOT_01?: string;
    MARKETPLACE_CREDENTIAL_KEY_SLOT_02?: string;
    MARKETPLACE_CREDENTIAL_KEY_SLOT_03?: string;
    MARKETPLACE_CREDENTIAL_KEY_SLOT_04?: string;
    MARKETPLACE_CREDENTIAL_KEY_SLOT_05?: string;
    MARKETPLACE_CREDENTIAL_KEY_SLOT_06?: string;
    MARKETPLACE_CREDENTIAL_KEY_SLOT_07?: string;
    MARKETPLACE_CREDENTIAL_KEY_SLOT_08?: string;
    MARKETPLACE_CREDENTIAL_LOOKUP_KEYRING?: string;
    MARKETPLACE_CREDENTIAL_LOOKUP_KEYRING_MANIFEST?: string;
    MARKETPLACE_CREDENTIAL_LOOKUP_KEY_SLOT_01?: string;
    MARKETPLACE_CREDENTIAL_LOOKUP_KEY_SLOT_02?: string;
    MARKETPLACE_CREDENTIAL_LOOKUP_KEY_SLOT_03?: string;
    MARKETPLACE_CREDENTIAL_LOOKUP_KEY_SLOT_04?: string;
    MARKETPLACE_CREDENTIAL_LOOKUP_KEY_SLOT_05?: string;
    MARKETPLACE_CREDENTIAL_LOOKUP_KEY_SLOT_06?: string;
    MARKETPLACE_CREDENTIAL_LOOKUP_KEY_SLOT_07?: string;
    MARKETPLACE_CREDENTIAL_LOOKUP_KEY_SLOT_08?: string;
    MARKETPLACE_CREDENTIAL_LOOKUP_LEGACY_ENABLED?: string;
    MARKETPLACE_CONTENT_KEY?: string;
    MARKETPLACE_COMMITMENT_KEY?: string;
    MARKETPLACE_MAINTENANCE_KEY?: string;
    MARKETPLACE_ADMIN_USER_IDS?: string;
    MARKETPLACE_GATEWAY_HOST_ALLOWLIST?: string;
    MARKETPLACE_PLATFORM_FEE_BPS?: string;
    MARKETPLACE_WELCOME_CREDIT_MICROS?: string;
  }
}
