import { promises as fs } from "node:fs";
import path from "node:path";
import type { RepoSummary } from "@token-streaming/protocol";
import { stringifySimpleYaml } from "./simple-yaml.js";

export interface GeneratedManifestResult {
  root: string;
  files: string[];
  created: string[];
  skipped: string[];
}

export interface ScaffoldManifestResult {
  root: string;
  created: string[];
  skipped: string[];
}

export interface ScaffoldManifestOptions {
  overwrite?: boolean;
}

const OFFICIAL_MANIFEST_FILES = [
  "project.md",
  "architecture.md",
  "conventions.md",
  "commands.yaml",
  "tests.yaml",
  "models.yaml",
  "ownership.yaml",
  "safety.yaml",
  "glossary.md"
] as const;

export async function generateFallbackManifest(
  repoRoot: string,
  summary: RepoSummary,
  options: ScaffoldManifestOptions = {}
): Promise<GeneratedManifestResult> {
  const generatedRoot = path.join(repoRoot, ".ai", "generated");
  await fs.mkdir(generatedRoot, { recursive: true });
  const created: string[] = [];
  const skipped: string[] = [];

  await writeGeneratedFile(
    generatedRoot,
    "project.md",
    [
      "# Generated Project Summary",
      "",
      "This file was generated by Token Streaming because no root `.ai/` manifest was found.",
      "",
      `Repository root: ${summary.root}`,
      `Package manager: ${summary.packageManager ?? "unknown"}`,
      "",
      "Review and promote this content into `.ai/project.md` when it is accurate."
    ].join("\n"),
    options,
    created,
    skipped
  );
  await writeGeneratedFile(
    generatedRoot,
    "architecture.md",
    [
      "# Generated Architecture Notes",
      "",
      "Detected source directories:",
      ...summary.sourceDirectories.map((directory) => `- ${directory}`),
      "",
      "Detected module manifests:",
      ...emptyAwareList(summary.moduleManifestPaths),
      "",
      "Detected workflow manifests:",
      ...emptyAwareList(summary.workflowManifestPaths)
    ].join("\n"),
    options,
    created,
    skipped
  );
  await writeGeneratedFile(generatedRoot, "commands.yaml", stringifySimpleYaml(inferCommandGroups(summary)), options, created, skipped);
  await writeGeneratedFile(
    generatedRoot,
    "tests.yaml",
    stringifySimpleYaml({
      default: inferTestCommands(summary)
    }),
    options,
    created,
    skipped
  );
  await writeGeneratedFile(
    generatedRoot,
    "repo-map.json",
    JSON.stringify(buildGeneratedRepoMap(summary), null, 2),
    options,
    created,
    skipped
  );

  return { root: generatedRoot, files: [...created, ...skipped], created, skipped };
}

export async function scaffoldOfficialManifest(
  repoRoot: string,
  summary: RepoSummary,
  options: ScaffoldManifestOptions = {}
): Promise<ScaffoldManifestResult> {
  const aiRoot = path.join(repoRoot, ".ai");
  const playbookRoot = path.join(aiRoot, "playbooks");
  await fs.mkdir(playbookRoot, { recursive: true });

  const created: string[] = [];
  const skipped: string[] = [];
  const packageManager = summary.packageManager ?? (isPythonRepository(summary) ? "Python" : "unknown");
  const testCommands = inferTestCommands(summary);
  const commandGroups = inferCommandGroups(summary);

  await writeOfficialFile(
    aiRoot,
    "project.md",
    [
      "# Project",
      "",
      "Describe the product purpose, target users, and the business context an agent needs before editing code.",
      "",
      `Repository root: ${summary.root}`,
      `Package manager: ${packageManager}`
    ].join("\n"),
    options,
    created,
    skipped
  );

  await writeOfficialFile(
    aiRoot,
    "architecture.md",
    [
      "# Architecture",
      "",
      "Describe the system boundaries, major modules, data flow, and architectural constraints.",
      "",
      "Detected source directories:",
      ...emptyAwareList(summary.sourceDirectories),
      "",
      "Detected module manifests:",
      ...emptyAwareList(summary.moduleManifestPaths),
      "",
      "Detected workflow manifests:",
      ...emptyAwareList(summary.workflowManifestPaths)
    ].join("\n"),
    options,
    created,
    skipped
  );

  await writeOfficialFile(
    aiRoot,
    "conventions.md",
    [
      "# Conventions",
      "",
      "Document naming rules, code style, review expectations, and project-specific implementation patterns.",
      "",
      "- Prefer explicit module boundaries.",
      "- Keep tests close to the source or document the mapping.",
      "- Update manifests when module responsibilities change.",
      "",
      "## Module manifests",
      "",
      "Place module manifests at `src/modules/<name>/module.yaml`, `packages/<name>/module.yaml`, or `apps/<name>/module.yaml`.",
      "Use these exact field names:",
      "",
      "```yaml",
      "name: example",
      "description: Clear module responsibility.",
      "owners:",
      "  - owning-team",
      "public_api:",
      "  - src/modules/example/api.js",
      "depends_on: []",
      "used_by: []",
      "test_commands:",
      "  - npm run test",
      "rules:",
      "  - Keep domain rules explicit.",
      "```"
    ].join("\n"),
    options,
    created,
    skipped
  );

  await writeOfficialFile(
    aiRoot,
    "commands.yaml",
    stringifySimpleYaml({
      install: inferInstallCommands(summary),
      build: commandGroups.build ?? [],
      test: commandGroups.test ?? [],
      lint: commandGroups.lint ?? [],
      typecheck: commandGroups.typecheck ?? []
    }),
    options,
    created,
    skipped
  );

  await writeOfficialFile(
    aiRoot,
    "tests.yaml",
    stringifySimpleYaml({
      default: testCommands.length > 0 ? testCommands : scriptCommand(summary, "test"),
      smoke: []
    }),
    options,
    created,
    skipped
  );

  await writeOfficialFile(
    aiRoot,
    "models.yaml",
    stringifySimpleYaml({
      default_provider: "codex",
      economy_model: "gpt-5.5-mini",
      auto_model: "gpt-5.5",
      max_model: "gpt-5.5",
      model_candidates: [
        "gpt-5.5-mini;provider=openai;quality=0.72;cost=0.25;latency=0.25;tags=economy,fast",
        "gpt-5.5;provider=openai;quality=0.94;cost=0.75;latency=0.55;tags=balanced,max"
      ]
    }),
    options,
    created,
    skipped
  );

  await writeOfficialFile(
    aiRoot,
    "ownership.yaml",
    stringifySimpleYaml({
      default_owner: "project-maintainers",
      owned_paths: ["src/**: engineering", ".ai/**: agent-platform"],
      review_required: ["security-sensitive", "public-api", "data-migration"]
    }),
    options,
    created,
    skipped
  );

  await writeOfficialFile(
    aiRoot,
    "safety.yaml",
    stringifySimpleYaml({
      sensitive_paths: [".env", ".env.*", "secrets/*"],
      protected_patterns: [
        "BEGIN (RSA |OPENSSH |EC )?PRIVATE KEY",
        "OPENAI_API_KEY\\s*=",
        "ANTHROPIC_API_KEY\\s*=",
        "GEMINI_API_KEY\\s*="
      ],
      approval_required_commands: ["npm publish", "pnpm publish", "netlify deploy --prod"],
      forbidden_commands: ["git reset --hard", "git checkout --"]
    }),
    options,
    created,
    skipped
  );

  await writeOfficialFile(
    aiRoot,
    "glossary.md",
    ["# Glossary", "", "Define domain terms, acronyms, and names that agents should treat as stable search anchors."].join("\n"),
    options,
    created,
    skipped
  );

  await writeOfficialFile(
    playbookRoot,
    "fix-failing-test.md",
    [
      "# Fix Failing Test",
      "",
      "When fixing a failing test:",
      "",
      "1. Read the failing output first.",
      "2. Identify the smallest source or test boundary involved.",
      "3. Apply a patch through the patch engine.",
      "4. Re-run the narrow failing command.",
      "5. Run the default verification command before finishing."
    ].join("\n"),
    options,
    created,
    skipped
  );

  return { root: aiRoot, created, skipped };
}

function inferTestCommands(summary: RepoSummary): string[] {
  const scriptCommands = inferTestScriptNames(summary.scripts).map((name) => `${summary.packageManager ?? "pnpm"} run ${name}`);
  const pythonCommands = inferPythonCommandGroups(summary);
  return [
    ...new Set([
      ...scriptCommands,
      ...(summary.verificationCommands ?? []),
      ...(pythonCommands.test ?? []),
      ...(pythonCommands.lint ?? []),
      ...(pythonCommands.typecheck ?? [])
    ])
  ];
}

function inferCommandGroups(summary: RepoSummary): Record<string, string[]> {
  const scriptGroups = Object.fromEntries(
    Object.keys(summary.scripts)
      .sort()
      .map((name) => [name, [`${summary.packageManager ?? "pnpm"} run ${name}`]])
  );
  const pythonGroups = inferPythonCommandGroups(summary);
  const install = inferInstallCommands(summary);
  return { ...(install.length ? { install } : {}), ...pythonGroups, ...scriptGroups };
}

function inferInstallCommands(summary: RepoSummary): string[] {
  if (summary.packageManager) {
    return [`${summary.packageManager} install`];
  }
  const files = new Set(summary.trackedFiles.map((file) => normalizeRepoPath(file).toLowerCase()));
  if (files.has("uv.lock")) {
    return ["uv sync"];
  }
  if (files.has("poetry.lock")) {
    return ["poetry install"];
  }
  if (files.has("requirements.txt")) {
    return ["python -m pip install -r requirements.txt"];
  }
  if (files.has("pyproject.toml") || files.has("setup.py")) {
    return ["python -m pip install -e ."];
  }
  return [];
}

function inferPythonCommandGroups(summary: RepoSummary): Record<string, string[]> {
  if (!isPythonRepository(summary)) {
    return {};
  }
  const files = summary.trackedFiles.map((file) => normalizeRepoPath(file).toLowerCase());
  const groups: Record<string, string[]> = {};
  if (files.some((file) => isTestFile(file)) || files.some((file) => /(^|\/)(pytest\.ini|conftest\.py)$/.test(file))) {
    groups.test = ["python -m pytest"];
  }
  if (files.some((file) => /(^|\/)(ruff\.toml|\.ruff\.toml)$/.test(file))) {
    groups.lint = ["python -m ruff check ."];
  }
  if (files.some((file) => /(^|\/)(mypy\.ini|\.mypy\.ini)$/.test(file))) {
    groups.typecheck = ["python -m mypy ."];
  }
  return groups;
}

function isPythonRepository(summary: RepoSummary): boolean {
  return summary.trackedFiles.some(
    (file) => /\.py$/i.test(file) || /(^|\/)(pyproject\.toml|requirements\.txt|setup\.py)$/i.test(normalizeRepoPath(file))
  );
}

function buildGeneratedRepoMap(summary: RepoSummary): Record<string, unknown> {
  const normalizedFiles = summary.trackedFiles.map(normalizeRepoPath);
  const moduleCandidates = inferModuleCandidates(normalizedFiles);
  const workflowCandidates = inferWorkflowCandidates(normalizedFiles);

  return {
    trackedFiles: summary.trackedFiles,
    sourceDirectories: summary.sourceDirectories,
    moduleManifestPaths: summary.moduleManifestPaths,
    workflowManifestPaths: summary.workflowManifestPaths,
    verificationCommands: summary.verificationCommands ?? [],
    inferredModules: moduleCandidates,
    inferredWorkflows: workflowCandidates,
    testMappings: inferTestMappings(normalizedFiles, moduleCandidates, workflowCandidates),
    notes: [
      "Generated candidates are heuristic mappings for inherited repositories.",
      "Promote accurate candidates into module.yaml or flow.yaml before treating them as authoritative."
    ]
  };
}

interface GeneratedModuleCandidate {
  name: string;
  root: string;
  confidence: "low" | "medium" | "high";
  evidence: string[];
  publicApiCandidates: string[];
  testCandidates: string[];
}

interface GeneratedWorkflowCandidate {
  name: string;
  root: string;
  confidence: "low" | "medium" | "high";
  evidence: string[];
  touches: string[];
  testCandidates: string[];
}

function inferModuleCandidates(files: string[]): GeneratedModuleCandidate[] {
  const groups = new Map<string, string[]>();
  for (const file of files) {
    const root = inferModuleRoot(file);
    if (!root) {
      continue;
    }
    groups.set(root, [...(groups.get(root) ?? []), file]);
  }

  return [...groups.entries()]
    .map(([root, groupFiles]) => {
      const publicApiCandidates = groupFiles.filter(isPublicApiCandidate).slice(0, 5);
      const testCandidates = groupFiles.filter(isTestFile).slice(0, 5);
      const evidence = [
        `${groupFiles.length} file(s) under ${root}`,
        publicApiCandidates.length ? `public API-like files: ${publicApiCandidates.join(", ")}` : undefined,
        testCandidates.length ? `tests: ${testCandidates.join(", ")}` : undefined
      ].filter((value): value is string => typeof value === "string");

      return {
        name: root.split("/").at(-1) ?? root,
        root,
        confidence: confidenceFor(groupFiles.length, publicApiCandidates.length, testCandidates.length),
        evidence,
        publicApiCandidates,
        testCandidates
      };
    })
    .sort((left, right) => scoreConfidence(right.confidence) - scoreConfidence(left.confidence) || left.root.localeCompare(right.root))
    .slice(0, 20);
}

function inferWorkflowCandidates(files: string[]): GeneratedWorkflowCandidate[] {
  const roots = new Map<string, string[]>();
  for (const file of files) {
    const root = inferWorkflowRoot(file);
    if (!root) {
      continue;
    }
    roots.set(root, [...(roots.get(root) ?? []), file]);
  }

  return [...roots.entries()]
    .map(([root, groupFiles]) => {
      const testCandidates = groupFiles.filter(isTestFile).slice(0, 5);
      const touches = inferWorkflowTouches(root, files);
      return {
        name: root.split("/").at(-1) ?? root,
        root,
        confidence: confidenceFor(groupFiles.length, touches.length, testCandidates.length),
        evidence: [
          `${groupFiles.length} workflow/use-case file(s) under ${root}`,
          touches.length ? `nearby module hints: ${touches.join(", ")}` : "no module hints detected",
          testCandidates.length ? `tests: ${testCandidates.join(", ")}` : "no workflow tests detected"
        ],
        touches,
        testCandidates
      };
    })
    .sort((left, right) => scoreConfidence(right.confidence) - scoreConfidence(left.confidence) || left.root.localeCompare(right.root))
    .slice(0, 20);
}

function inferTestMappings(
  files: string[],
  modules: GeneratedModuleCandidate[],
  workflows: GeneratedWorkflowCandidate[]
): Array<{ target: string; tests: string[]; reason: string }> {
  const mappings = [
    ...modules.map((module) => ({
      target: module.root,
      tests: module.testCandidates.length ? module.testCandidates : nearbyTests(files, module.name),
      reason: "Module candidate matched tests by directory or name."
    })),
    ...workflows.map((workflow) => ({
      target: workflow.root,
      tests: workflow.testCandidates.length ? workflow.testCandidates : nearbyTests(files, workflow.name),
      reason: "Workflow candidate matched tests by directory or name."
    }))
  ];
  return mappings.filter((mapping) => mapping.tests.length > 0);
}

function inferModuleRoot(file: string): string | undefined {
  const parts = file.split("/");
  for (const root of ["src/modules", "packages", "apps", "services", "lib"]) {
    const rootParts = root.split("/");
    if (rootParts.every((part, index) => parts[index] === part) && parts.length > rootParts.length + 1) {
      return parts.slice(0, rootParts.length + 1).join("/");
    }
  }
  if (parts[0] === "app" && parts.length > 2) {
    return parts.slice(0, 2).join("/");
  }
  if (parts[0] === "src" && parts.length > 2 && isPythonSourceFile(file)) {
    return parts.slice(0, 2).join("/");
  }
  if (parts[0] === "src" && parts.length > 2 && /api|service|repository|controller|route|schema|provider/i.test(parts.at(-1) ?? "")) {
    return parts.slice(0, 2).join("/");
  }
  return undefined;
}

function inferWorkflowRoot(file: string): string | undefined {
  const parts = file.split("/");
  for (const root of ["src/workflows", "src/use-cases", "src/usecases", "workflows", "use-cases", "features"]) {
    const rootParts = root.split("/");
    if (rootParts.every((part, index) => parts[index] === part) && parts.length > rootParts.length + 1) {
      return parts.slice(0, rootParts.length + 1).join("/");
    }
  }
  if (/workflow|flow|checkout|onboarding|payment|signup/i.test(file) && !isTestFile(file)) {
    return path.posix.dirname(file);
  }
  return undefined;
}

function inferWorkflowTouches(root: string, files: string[]): string[] {
  const tokens = root
    .toLowerCase()
    .split(/[^a-z0-9]+/)
    .filter((token) => token.length > 3);
  const moduleRoots = new Set(files.map(inferModuleRoot).filter((value): value is string => typeof value === "string"));
  return [...moduleRoots].filter((moduleRoot) => tokens.some((token) => moduleRoot.toLowerCase().includes(token))).slice(0, 8);
}

function nearbyTests(files: string[], name: string): string[] {
  const normalizedName = name.toLowerCase();
  return files.filter((file) => isTestFile(file) && file.toLowerCase().includes(normalizedName)).slice(0, 5);
}

function isPublicApiCandidate(file: string): boolean {
  return /(^|\/)(index|api|route|routes|controller|schema|service)\.(ts|tsx|js|jsx|mjs|cjs)$/i.test(file)
    || /(^|\/)(__init__|main|train|eval)\.py$/i.test(file);
}

function isTestFile(file: string): boolean {
  return /(^|\/)(__tests__|tests?|specs?)(\/|$)|\.(test|spec)\.(ts|tsx|js|jsx|mjs|cjs)$/i.test(file)
    || /(^|\/)test_[^/]+\.py$/i.test(file)
    || /(^|\/)[^/]+_test\.py$/i.test(file);
}

function isPythonSourceFile(file: string): boolean {
  return /\.py$/i.test(file) && !isTestFile(file);
}

function confidenceFor(fileCount: number, publicOrTouchCount: number, testCount: number): GeneratedModuleCandidate["confidence"] {
  const score = Math.min(3, fileCount / 4) + publicOrTouchCount + testCount;
  if (score >= 4) {
    return "high";
  }
  if (score >= 2) {
    return "medium";
  }
  return "low";
}

function scoreConfidence(confidence: GeneratedModuleCandidate["confidence"]): number {
  return confidence === "high" ? 3 : confidence === "medium" ? 2 : 1;
}

function normalizeRepoPath(file: string): string {
  return file.replace(/\\/g, "/");
}

function inferTestScriptNames(scripts: Record<string, string>): string[] {
  return Object.keys(scripts)
    .filter((name) => /test|check|lint|type/i.test(name) && !isPlaceholderTestScript(scripts[name] ?? ""));
}

function scriptCommand(summary: RepoSummary, script: string): string[] {
  const command = summary.scripts[script];
  if (!command || (script === "test" && isPlaceholderTestScript(command))) {
    return [];
  }
  return [`${summary.packageManager ?? "pnpm"} run ${script}`];
}

function isPlaceholderTestScript(command: string): boolean {
  const normalized = command.toLowerCase().replace(/\s+/g, " ");
  return normalized.includes("no test specified") || normalized.includes("no tests specified") || normalized.includes("no test configured");
}

function emptyAwareList(values: string[]): string[] {
  return values.length > 0 ? values.map((value) => `- ${value}`) : ["- none detected"];
}

async function writeGeneratedFile(
  root: string,
  name: string,
  content: string,
  options: ScaffoldManifestOptions,
  created: string[],
  skipped: string[]
): Promise<void> {
  const fullPath = path.join(root, name);
  if (!options.overwrite && (await exists(fullPath))) {
    skipped.push(fullPath);
    return;
  }
  await fs.writeFile(fullPath, `${content.trimEnd()}\n`, "utf8");
  created.push(fullPath);
}

async function writeOfficialFile(
  root: string,
  name: string,
  content: string,
  options: ScaffoldManifestOptions,
  created: string[],
  skipped: string[]
): Promise<void> {
  const fullPath = path.join(root, name);
  if (!options.overwrite && (await exists(fullPath))) {
    skipped.push(fullPath);
    return;
  }

  await fs.mkdir(path.dirname(fullPath), { recursive: true });
  await fs.writeFile(fullPath, `${content.trimEnd()}\n`, "utf8");
  created.push(fullPath);
}

async function exists(filePath: string): Promise<boolean> {
  try {
    await fs.access(filePath);
    return true;
  } catch (error) {
    if (error instanceof Error && "code" in error && error.code === "ENOENT") {
      return false;
    }
    throw error;
  }
}
